import Output from './src/output';
import { Loop } from './src/loop';
import Source from './src/hydra-source';
import VidRecorder from './src/lib/video-recorder';
import Sandbox from './src/eval-sandbox';
import { DrawCommand, Regl } from 'regl';
import Generator from './src/generator-factory';
import { TransformDefinition } from './src/glsl/glsl-functions';
declare const Mouse: any;
export declare type Precision = 'lowp' | 'mediump' | 'highp';
export interface Synth {
    time: number;
    bpm: number;
    width: number;
    height: number;
    fps?: number;
    stats: {
        fps: number;
    };
    speed: number;
    mouse: typeof Mouse;
    render: any;
    setResolution: any;
    update?: (dt: number) => void;
    hush: any;
    screencap?: () => void;
    vidRecorder?: VidRecorder;
    [name: string]: any;
}
interface HydraRendererOptions {
    pb?: HydraRenderer['pb'];
    width?: HydraRenderer['width'];
    height?: HydraRenderer['height'];
    numSources?: number;
    numOutputs?: number;
    makeGlobal?: boolean;
    autoLoop?: boolean;
    detectAudio?: HydraRenderer['detectAudio'];
    enableStreamCapture?: boolean;
    regl: HydraRenderer['regl'];
    precision?: HydraRenderer['precision'];
    extendTransforms?: HydraRenderer['extendTransforms'];
}
declare class HydraRenderer implements HydraRendererOptions {
    pb?: any | null;
    width: number;
    height: number;
    detectAudio?: boolean;
    synth: Synth;
    timeSinceLastUpdate: number;
    _time: number;
    precision: Precision;
    extendTransforms: TransformDefinition | TransformDefinition[];
    saveFrame: boolean;
    captureStream: MediaStream | null;
    generator?: Generator;
    sandbox: Sandbox;
    imageCallback?: (blob: Blob | null) => void;
    regl: Regl;
    renderAll: DrawCommand | false;
    renderFbo: DrawCommand;
    isRenderingAll: boolean;
    s: Source[];
    o: Output[];
    output: Output;
    loop: Loop;
    [name: string]: any;
    constructor({ pb, width, height, numSources, numOutputs, makeGlobal, autoLoop, detectAudio, enableStreamCapture, precision, regl, extendTransforms, }: HydraRendererOptions);
    hush: () => void;
    setResolution: (width: number, height: number) => void;
    canvasToImage(): void;
    _initRegl(): void;
    _initOutputs(numOutputs: number): void;
    _initSources(numSources: number): void;
    createSource(i: number): Source;
    _generateGlslTransforms(): void;
    _render: (output: Output) => void;
    tick: (dt: number) => void;
}
export default HydraRenderer;
